### ISSUE TITLE
ValueError: could not convert string to float: '3.3\x00'

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [ratcashdev/mitemp#4]
I got this error with Home Assistant
0.82.1:
```
Update for sensor.outsidebalkon_temperature fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/mitemp_bt.py", line 142, in update
    data = self.poller.parameter_value(self.parameter)
  File "/srv/homeassistant/lib/python3.5/site-packages/mitemp_bt/mitemp_bt_poller.py", line 132, in parameter_value
    return self._parse_data()[parameter]
  File "/srv/homeassistant/lib/python3.5/site-packages/mitemp_bt/mitemp_bt_poller.py", line 177, in _parse_data
    res[MI_HUMIDITY] = float(data[9:13])
ValueError: could not convert string to float: '3.3\x00'
```
**Hardware**: RPi3 B+
**Bluetooth**: OnBoard
**Network over**: LAN

> myUser@raspberrypi:~ $ dpkg --status bluez | grep ‘^Version:’
> Version: 5.43-2+rpt2+deb9u2

Because of my bluez version and this bug [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690749), I add this line to the /etc/bluetooth/main.conf

`DisablePlugins=pnat
`
Here is another mi_bt_poller, perhaps it helps: https://github.com/pFenners/mijia-sensor-domoticz/blob/master/mijia/mijia_poller.py

I dont think that my config is the problem. Here is my config snip: [Home-Assistant Community](https://community.home-assistant.io/t/xiaomi-ble-temperature-and-humidity-sensor/61423/19)

Greetings by uniat

**Comment by ratcashdev** [comment]
should be fixed.

**Comment by remoe** [comment]
I don't think this is fixed:

```
File "/srv/homeassistant/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 195, in handleNotification
  return
File "/srv/homeassistant/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 144, in _check_data
File "/srv/homeassistant/lib/python3.7/site-packages/mitemp_bt/mitemp_bt_poller.py", line 177, in _parse_data
  dataparts = dataitem.split('=')
ValueError: could not convert string to float: '3.5\x00'
```

**Comment by remoe** [comment]
Ok, it works ;) One need to update this component in a different way:

```
pip3 install 'mitemp_bt==0.0.3' --target ~/.homeassistant/deps
```

and then run homeassistant with

```
hass --skip-pip
```

Found here:
https://developers.home-assistant.io/docs/en/creating_integration_manifest.html#custom-requirements-during-development-testing

**Comment by ratcashdev** [comment]
@remoe you may want to submit an issue for HA to upgrade the dependency.
I guess this one could be closed.
